---
apiVersion: batch/v1
kind: Job
metadata:
  name: rollouts-add-host-job
  namespace: apps
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    metadata:
      name: rollouts-add-host-job
    spec:
      restartPolicy: Never
      serviceAccountName: rollouts-foo-app1-ingress-sa
      containers:
      - name: cmd-exec
        image: public.ecr.aws/i4a3l2a7/cmd-exec:latest
        env:
        - name: FILE_NAME
          value: "ingress-patch.yaml"
        - name: FILE_CONTENTS_INGRESS
          value: |
            - op: add
              path: /spec/rules/-
              value:
                host: green.foobarbbq.com
                http:
                  paths:
                    - backend:
                        service:
                          name: rollouts-foo-app1-preview
                          port:
                            name: svc-port
                      path: /
                      pathType: Prefix
        command: [ '/bin/bash', '-c' ]
        args:
         - echo "${FILE_CONTENTS_INGRESS}" > /tmp/${FILE_NAME};
           cat /tmp/${FILE_NAME};
           kubectl patch ingress rollouts-foo-app1-ingress -n apps --type=json --patch-file=/tmp/${FILE_NAME};
