---
apiVersion: batch/v1
kind: Job
metadata:
  name: rollouts-add-host-job
  namespace: apps
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    metadata:
      name: rollouts-add-host-job
    spec:
      restartPolicy: Never
      serviceAccountName: rollouts-foo-ingress-sa
      containers:
      - name: cmd-exec
        image: public.ecr.aws/i4a3l2a7/cmd-exec:latest
        env:
        - name: FILE_NAME
          value: "ingress-patch.yaml"
        - name: FILE_CONTENTS_INGRESS
          value: |
            - op: add
              path: /spec/rules/-
              value:
                host: green.foobarbbq.com
                http:
                  paths:
                    - backend:
                        service:
                          name: rollouts-foo-app1-preview
                          port:
                            name: svc-port
                      path: /
                      pathType: Prefix
#         - name: FILE_CONTENTS_SERVICE
#           value: |
#             apiVersion: v1
#             kind: Service
#             metadata:
#               name: rollouts-foo-app1-preview
#               namespace: apps
#               labels:
#                 app: rollouts-foo-app1
#             spec:
#               ports:
#                 - name: svc-port
#                   port: 80
#                   protocol: TCP
#                   targetPort: 80
#               selector:
#                 app: rollouts-foo-app1
#               type: ClusterIP
        command: [ '/bin/bash', '-c' ]
        args:
         - kubectl get -n apps ingress rollouts-foo-ingress >/dev/null 2>&1;
           RC=$?;
           [[ ${RC} -ne 0 ]] && {
               echo "Error - The Ingress object rollouts-foo-ingress does not exist";
               exit 0;
           };
           echo "${FILE_CONTENTS_INGRESS}" > /tmp/${FILE_NAME};
           cat /tmp/${FILE_NAME};
           kubectl patch ingress rollouts-foo-ingress -n apps --type=json --patch-file=/tmp/${FILE_NAME};
