---
apiVersion: batch/v1
kind: Job
metadata:
  name: rollouts-remove-host-job
  namespace: apps
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 0
  template:
    metadata:
      name: rollouts-remove-host-job
    spec:
      restartPolicy: Never
      serviceAccountName: rollouts-foo-ingress-sa
      containers:
      - name: cmd-exec
        image: public.ecr.aws/i4a3l2a7/cmd-exec:latest
        env:
        - name: FILE_NAME
          value: "ingress-patch.yaml"
        - name: FILE_CONTENTS_INGRESS
          value: |
            - op: remove
              path: /spec/rules/__INDEX__
        command: [ '/bin/bash', '-c' ]
        args:
         - INDEX=$(kubectl get ingress rollouts-foo-ingress -n apps -o json | jq -rM '.spec.rules | map(.host == "green.foobarbbq.com") | index(true)');
           echo "${FILE_CONTENTS_INGRESS}" | sed -e "s/__INDEX__/${INDEX}/" > /tmp/${FILE_NAME};
           kubectl patch ingress rollouts-foo-ingress -n apps --type=json --patch-file=/tmp/${FILE_NAME};
           # kubectl -n apps delete service rollouts-foo-preview
