---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-foo-app1-active
  namespace: apps
  labels:
    app: rollouts-foo-app1
spec:
  ports:
    - name: svc-port
      port: 80
      protocol: TCP
      targetPort: 80
      # nodePort: 30090
  selector:
    app: rollouts-foo-app1
  # type: NodePort
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-foo-app1-preview
  namespace: apps
  labels:
    app: rollouts-foo-app1
spec:
  ports:
    - name: svc-port
      port: 80
      protocol: TCP
      targetPort: 80
      # nodePort: 30091
  selector:
    app: rollouts-foo-app1
  # type: NodePort
  type: ClusterIP
